### ISSUE TITLE
Select组件会导致代码抛出异常

### ISSUE THREAD

**Issue by iplus26** [ElemeFE/element-react#785]
### Description

Element 用到了 [javascript-detect-element-resize](https://github.com/eleme/element-react/blob/fedd46d004fbfed2d5e6045c1f0746b5fe44b77f/libs/utils/resize-event.js#L183) 来控制resize事件。具体是在 `TableLayout`, `Select` 等组件中 `componentWillUnmount` 的时候调用 `removeResizeListener` 方法. 该方法会操作`element.__resizeListeners__`这个数组，这个数组是在`addResizeListener`中初始化的，即如果element不先调用add 方法的话，而直接调用remove方法就会抛出异常
![image](https://user-images.githubusercontent.com/6082721/39912913-c6dc92c0-54c5-11e8-8604-f2329c4361fb.png)

Table中是在`componentDidMount`中调用了`addResizeListener`方法，在unmount的时候调用remove是完全OK的

Select组件是在`componentDidUpdate` 中调用了`addResizeListener`方法，在部分场景下该生命周期函数没执行，就会调用`componentWillUnmount`（如快速切换页面时 Select组件刚mount就被销毁了） 这个时候会触发报错

### Reproduce Steps

1. [First Step]
2. [Second Step]
3. [and so on...]

### Error Trace (if possible)

It's better to post up the error stack for us to trace this issue.

### Solution

Select组件也在`componentDidMount`中调用`addResizeListener`方法 保证`__resizeListener__`一定注册在element上

周末有时间的话我会提一个pr

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by iplus26** [comment]
[buggy lines](https://github.com/eleme/element-react/blob/master/src/select/Select.jsx#L151-L157)

**Comment by lucduong** [comment]
@iplus26 Do you have any update from this?

**Comment by iplus26** [comment]
@lucduong Not sure that this repo is actively maintained. Switched to ant design already.

**Comment by iplus26** [comment]
There're other issues about this problem, like #814 #781

**Comment by iplus26** [comment]
Should be fixed in https://github.com/ElemeFE/element-react/commit/aacec99e00df7ee3862b0287374218f8c1760545
Not published but I'll close this issue.
