### ISSUE TITLE
Select快速mount和unmount的时候，react-resize报错

### ISSUE THREAD

**Issue by zjy01** [ElemeFE/element-react#814]
### Description
界面默认展示Select，但是由于逻辑，快熟取消Select的展示，这时候，就会出现报错，整个页面奔溃

![image](https://user-images.githubusercontent.com/9987291/42150516-c754b3d8-7d9f-11e8-842c-a82fdcf3ea20.png)

### Reproduce Steps

1. a = true 的时候，render 一个 Select
2. 在mount做一个异步操作，设置 a = false

### Error Trace (if possible)
![image](https://user-images.githubusercontent.com/9987291/42150540-d1c4e9b4-7d9f-11e8-9b1a-49d9e4a579f6.png)

**Comment by mytharcher** [comment]
我看这个 PR 已经合并且在 1.4.20 中发布了，但是尝试新版本后发现并没有解决，依然会报错。具体原因应该是当没有子选项时，且下拉列表未渲染过，在移除组件的生命周期触发了 resize 相关事件，导致找不到列表元素和相关方法出错。

**Comment by xiang510** [comment]
It  must happend when i reload page where Select component .

**Comment by xiang510** [comment]
thanks @zjy01  . I got it.
