### ISSUE TITLE
[Select] in multi-select mode, change value can trigger OnChange?

### ISSUE THREAD

**Issue by RainWangjie** [ElemeFE/element-react#820]
Select component single-select mode, external event change value will not trigger Select OnChange event; in multi-select mode, external event changes value (this is an Array), value length change will trigger OnChange. Why is this designed?

https://github.com/ElemeFE/element-react/blob/master/src/select/Select.jsx#L145

If the initial value of value is an empty array, the external event (mobx action) is assigned, and it will enter the render infinite loop.
Change #146 to `this.onSelectedChange(state.selected,false)` can solve this problem.

Select组件单选模式，外部事件改变value不会触发Select的OnChange事件；多选模式下，外部事件改变value（此时是个Array）,value的length变化会触发OnChange。为什么这么设计？
如果value初始值为空数组，外部事件（mobx的action）赋值，就会进入render死循环
将#146改为 `this.onSelectedChange(state.selected，false)`取消这个逻辑就没问题。

**Comment by dpgirl** [comment]
@RainWangjie 您好，我也遇到这个问题，请问你是直接在项目的源码改吗？还有没有别的办法？

**Comment by RainWangjie** [comment]
> @RainWangjie 您好，我也遇到这个问题，请问你是直接在项目的源码改吗？还有没有别的办法？

是的，这是bug，只能修改源码。已改用antd

**Comment by dpgirl** [comment]
好的，谢谢

**Comment by dpgirl** [comment]
@RainWangjie 我找到新的办法了，不用改源码。
赋值用toggleRowSelection， toggleRowSelection(row, selected)接受两个参数，row传递被勾选行的数据，selected设置是否选中，true表示选中
原文：https://blog.csdn.net/gao_xu_520/article/details/80049781
![image](https://user-images.githubusercontent.com/22952830/69030029-5b421280-0a11-11ea-924d-571d91e794b0.png)
