### ISSUE TITLE
Upload缺少limit、disabled等参数

### ISSUE THREAD

**Issue by fanmzdj** [ElemeFE/element-react#822]
### Description
缺少必要的几个参数：
disabled | 是否禁用 | boolean |
limit | 最大允许上传个数 | number
on-exceed | 文件超出个数限制时的钩子 | function(files, fileList)

### Solution
希望添加限制上传个数的参数功能；

**Comment by canon4ever** [comment]
limit至今都没有

**Comment by canon4ever** [comment]
我喜欢用这个，不喜欢 antd。但这个也太不完善了点

**Comment by loadchange** [comment]
`limit ` 、`on-exceed ` 、`disabled ` 都有实现 ，如果使用有问题可以贴一下 `jsfiddle` 的代码片段
