### ISSUE TITLE
Slider onChange not working if `min` is set

### ISSUE THREAD

**Issue by sigtm** [ElemeFE/element-react#901]
### Description

If you do `<Slider min={10} onChange={someFunction}>`, `someFunction` is not called.

### Reproduce Steps

1. https://codesandbox.io/s/48npmx5kw9
2. Drag the slider, and notice that the updated value is printed in the console
3. Remove the `//` on line 13 to set the `min` property
4. Drag the slider again, and notice that onChange no longer fires

### Solution

I'm just a designer who sometimes hacks things, so it's not immediately obvious to me where the bug is or how to fix it – sorry.

**Comment by guciek27** [comment]
I've got the same issue!
