### ISSUE TITLE
Form 表单验证不通过会报 `Uncaught (in promise) `错误

### ISSUE THREAD

**Issue by zhaosheng808** [ElemeFE/element-react#902]
```
"element-react": "^1.4.21",
```
### Description
表单验证不通过会报错
```
Uncaught (in promise) {errors: Array(1), fields: {…}}
```
导致页面非常卡顿，电脑差的直接崩溃
### Reproduce Steps
使用方式和官网dome一样，并且设置`trigger: 'blur'`无效。只要输入就会报错，不会失去焦点才验证。

![image](https://user-images.githubusercontent.com/26834525/50198010-b0e6e880-0384-11e9-9665-293c3e6fc7b6.png)

### Error Trace (if possible)
![image](https://user-images.githubusercontent.com/26834525/50197871-1686a500-0384-11e9-9982-4172e673268a.png)

--------------------------update------------------

经过测试升级到 "element-theme-default": "^1.4.25", 不会出现这个错误，但是验证的trigger:blur选项还是无效， 

测试回退到 "element-theme-default": "^1.4.13", 验证规则可正常使用,但是其他组件好像有差异。。。

**Comment by zhaosheng808** [comment]
经过测试升级到 ` "element-theme-default": "^1.4.25",` 不会出现这个错误，但是验证的`trigger:blur`选项还是无效， 测试回退到 ` "element-theme-default": "^1.4.13",` 可正常使用

**Comment by ShenTiger** [comment]
I suggest you add 'catch' before the error.
like this
form.validateFields().then(res=>{}).catch(err=>{});
